[glock]
name = "Glack"
clip_size = 16
clips = 7
damage = 33.4
# Fraction of damage that will ignore armour (max 1)
penetration = 0.24
# Seconds between each shot
fire_rate = 0.25
reload_time = 1.6
fire_mode = "SemiAutomatic"
shot_snd = "shot2"
# Optional, this is the default value.
cock_snd = "cock"
click_snd = "click_pistol"
# Optional, this is the default value.
reload_snd = "reload"
# Optional, this is the default value.
impact_snd = "impact"
entity_sprite = "weapons/glock"
# Degrees your shoots will deviate from the direction fired for each consecutive shot
spray_pattern = [6.0, -8.0, 4.0, -6.0, 2.5, 6.0, 4.0]
# Seconds to decay of spray deviation
spray_decay = 0.43
# How many of the last elements will be repeated
spray_repeat = 2
# Speed of bullet in pixels per second
# Optional, this is the default value
bullet_speed = 1200

[five_seven]
name = "5-SeveN"
clip_size = 20
clips = 5
damage = 42.0
penetration = 0.46
fire_rate = 0.20
reload_time = 1.3
fire_mode = "SemiAutomatic"
shot_snd = "shot1"
click_snd = "click_pistol"
entity_sprite = "weapons/five_seven"
spray_pattern = [4.0, 6.0, -8.0, 4.0, -6.0, 4.0, -8.0, 6.0, 4.0]
spray_decay = 0.34
spray_repeat = 5

[magnum]
name = "500-MG"
clip_size = 5
clips = 4
damage = 111.0
penetration = 0.05
fire_rate = 0.72
reload_time = 3.2
fire_mode = "SemiAutomatic"
shot_snd = "shot1"
cock_snd = "cock2"
click_snd = "click_pistol"
entity_sprite = "weapons/magnum"
spray_pattern = [6.0, 2.0, -2.0]
spray_decay = 0.85
spray_repeat = 2
bullet_speed = 1600

[m4a1]
name = "M4A1"
clip_size = 30
clips = 3
damage = 62.0
penetration = 0.51
fire_rate = 0.075
reload_time = 2.8
fire_mode = "Automatic"
shot_snd = "shot1"
cock_snd = "cock_ak47"
click_snd = "click_uzi"
reload_snd = "reload_m4"
entity_sprite = "weapons/m4"
spray_pattern = [3.3, 4.2, -3.0, 3.0, -3.0, 2.0, -4.0, 3.0, 2.0]
spray_decay = 0.2
spray_repeat = 5
bullet_speed = 2000

[ak47]
name = "AK-47"
clip_size = 30
clips = 3
damage = 75.0
penetration = 0.22
fire_rate = 0.09
reload_time = 2.6
fire_mode = "Automatic"
shot_snd = "shot1"
cock_snd = "cock_ak47"
click_snd = "click_uzi"
entity_sprite = "weapons/ak47"
spray_pattern = [-3.3, -4.2, 3.0, -3.0, 3.0, -2.0, 4.0, -3.0, -2.0, 3.0]
spray_decay = 0.13
spray_repeat = 5
bullet_speed = 1800

[arwp]
name = "ARWP"
clip_size = 10
clips = 4
damage = 130.0
penetration = 0.8
fire_rate = 0.92
reload_time = 3.5
fire_mode = "BoltAction"
shot_snd = "shot1"
cock_snd = "cock2"
click_snd = "click_pistol"
reload_snd = "reload_m4"
entity_sprite = "weapons/arwp"
spray_pattern = [5.6, 1.0, -1.0]
spray_decay = 1.0
spray_repeat = 2
bullet_speed = 3200

[sawblade_launcher]
name = "Sawblade launcher"
clip_size = 3
clips = 5
damage = 42.5
penetration = 0.35
fire_rate = 0.45
reload_time = 1.85
bullet_type = "SawBlade"
bullet_speed = 500.0
fire_mode = "BoltAction"
shot_snd = "throw"
cock_snd = "cock2"
click_snd = "click_uzi"
entity_sprite = "weapons/saw_blade_gun"
spray_pattern = [-1.0, 1.0, 2.0, -2.0]
spray_decay = 0.53
spray_repeat = 2


[laser_rifle]
name = "Laser Sniper"
clip_size = 6
clips = 8
damage = 168.5
penetration = 0.1
fire_rate = 0.15
reload_time = 1.95
bullet_type = "Laser"
bullet_speed = 2200.0
fire_mode = "SemiAutomatic"
shot_snd = "boom"
cock_snd = "cock2"
click_snd = "click_uzi"
entity_sprite = "weapons/laser_rifle"
spray_pattern = [-0.5, 0.5, 0.75, -0.75]
spray_decay = 0.53
spray_repeat = 2

[auto_laser]
name = "Auto-Laser"
clip_size = 60
clips = 3
damage = 16.5
penetration = 0.1
fire_rate = 0.09
reload_time = 3.95
bullet_type = "Laser"
bullet_speed = 2200.0
fire_mode = "Automatic"
shot_snd = "boom"
cock_snd = "cock2"
click_snd = "click_uzi"
entity_sprite = "weapons/auto_laser"
# spray_pattern = [-0.5, 0.5, 0.75, -0.75,]
spray_pattern = [-1.3, -2.2, 3.4, -3.2, 2.8, -2.0, 3.0, -1.2, 1.5, -2.8]
spray_decay = 0.43
spray_repeat = 4


[shotgun]
name = "shotgun"
clip_size = 6
clips = 4
damage = 9.5
penetration = 0.08
fire_rate = 0.56
reload_time = 2.4
bullet_type = "Shotgun"
bullet_amount = 12
fire_mode = "SemiAutomatic"
shot_snd = "shot1"
cock_snd = "cock2"
click_snd = "click_pistol"
entity_sprite = "weapons/shotgun"
spray_pattern = [-1.4, 1.25, -1.3, 2.2, -3.5, 3.3, 5.3, -6.8, 4.1, -2.6, 6.8, -6.2]
spray_decay = 0.85
spray_repeat = 4
bullet_speed = 1600

[break_action_shotgun]
name = "break action shotgun"
clip_size = 2
clips = 14
damage = 15.2
penetration = 0.12
fire_rate = 0.12
reload_time = 1.6
bullet_type = "Shotgun"
bullet_amount = 12
fire_mode = "SemiAutomatic"
shot_snd = "shot1"
cock_snd = "cock2"
click_snd = "click_pistol"
entity_sprite = "weapons/break_action_shotgun"
spray_pattern = [-1.3, 2.2, -3.5, 3.2, 2.6, -2.7, 0.2, -2.1, 1.4, -1.8, -0.4, 0.25]
spray_decay = 0.85
spray_repeat = 4
bullet_speed = 1200